# Generated by Django 4.0.4 on 2022-05-30 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fifi', '0002_registration_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='fullname',
            new_name='name',
        ),
    ]
