-- MySQL Script generated by MySQL Workbench
-- mer. 18 mai 2022 09:18:46
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema testbb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema testbb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `testbb` ;
USE `testbb` ;

-- -----------------------------------------------------
-- Table `testbb`.`articles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `testbb`.`articles` (
  `idarticles` INT NOT NULL,
  `nomarticle` VARCHAR(45) NULL,
  `nbvues` INT NULL,
  `datepub` DATE NULL,
  PRIMARY KEY (`idarticles`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `testbb`.`entreprise`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `testbb`.`entreprise` (
  `identreprise` INT NOT NULL,
  `nomentrp` VARCHAR(45) NULL,
  `enbvues` INT NULL,
  PRIMARY KEY (`identreprise`),
  CONSTRAINT `fk_nomarticle`
    FOREIGN KEY ()
    REFERENCES `testbb`.`articles` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `testbb` ;

-- -----------------------------------------------------
-- Placeholder table for view `testbb`.`view1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `testbb`.`view1` (`id` INT);

-- -----------------------------------------------------
-- View `testbb`.`view1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `testbb`.`view1`;
USE `testbb`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
